### ISSUE TITLE
Authorized Failed

### ISSUE THREAD

**Issue by UmairAhmed420** [CMARIXTechnolabs/twitter-login-android#2]
com.twitter.sdk.android.core.TwitterAuthException: Authorize failed.
        at com.twitter.sdk.android.core.identity.TwitterAuthClient.handleAuthorize(TwitterAuthClient.java:112)
        at com.twitter.sdk.android.core.identity.TwitterAuthClient.authorize(TwitterAuthClient.java:103)

**Comment by ArunkarthickNallasamy** [comment]
Add 

> twittersdk://

 callback
